class MealItem {
  final String name;
  final String calories;
  final String protein;
  MealItem(this.name, [this.calories = '', this.protein = '']);
}

class DailyMenu {
  final String dateText;
  final List<String> breakfast;
  final List<String> salad;
  final List<MealItem> mainCourse;
  final String totalCalories;
  final String totalProtein;
  const DailyMenu({required this.dateText, required this.breakfast, required this.salad, required this.mainCourse, required this.totalCalories, this.totalProtein = ''});
}

class MenuData {
  static final Map<int, DailyMenu> augustMenu = {
    1: DailyMenu(
      dateText: '1 Ağustos Cumartesi',
      breakfast: ['Şehriye Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Ayranaşı', 'Kısır', 'Aysberg', 'Marineli Beyaz Lahana'],
      totalCalories: '1.514',
      totalProtein: '38g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Patates Musakka', '468', '15g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Browni', '349', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    2: DailyMenu(
      dateText: '2 Ağustos Pazar',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Cacık', 'Humus', 'Domates Söğüş', 'Havuç Rende'],
      totalCalories: '1.403',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Biber Dolma', '461', '15g'), MealItem('Barbunya Pilaki', '363', '14g'), MealItem('Komposto', '223', '1g'), MealItem('Yoğurt', '81', '7g')],
    ),
    3: DailyMenu(
      dateText: '3 Ağustos Pazartesi',
      breakfast: ['Yayla Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Ispanaklı Kol Böreği', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Fırın Patates', 'Sumaklı Soğan', 'Turşu'],
      totalCalories: '1.383',
      totalProtein: '53g',
      mainCourse: [MealItem('Anadolu Çorba', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    4: DailyMenu(
      dateText: '4 Ağustos Salı',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Karpuz', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Yoğ.Makarna', 'Fırın Mücver', 'Biber Söğüş', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.617',
      totalProtein: '43g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Taze Fasulye', '374', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Yoğurt Tatlısı', '524', '7g'), MealItem('Yoğurt', '81', '7g')],
    ),
    5: DailyMenu(
      dateText: '5 Ağustos Çarşamba',
      breakfast: ['Şehriye Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Pancarlı Şehriye Salatası', 'Domates Söğüş', 'Salatalık Söğüş'],
      totalCalories: '1.217',
      totalProtein: '49g',
      mainCourse: [MealItem('Yayla Çorba', '234', '7g'), MealItem('Sebzeli Tavuk Kebabı', '425', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    6: DailyMenu(
      dateText: '6 Ağustos Perşembe',
      breakfast: ['Ezogelin Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Çoban Salata', 'Yoğ.Patlıcan', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.357',
      totalProtein: '48g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Sütlaç', '242', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    7: DailyMenu(
      dateText: '7 Ağustos Cuma',
      breakfast: ['Domates Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'H.Yumurta', 'Üzümlü Kek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Rus Salatası', 'Fırın Biber', 'Marineli Beyaz Lahana'],
      totalCalories: '1.245',
      totalProtein: '43g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Hasanpaşa Köfte', '441', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    8: DailyMenu(
      dateText: '8 Ağustos Cumartesi',
      breakfast: ['Mercimek Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Cacık', 'Kısır', 'Aysberg', 'Domates Söğüş'],
      totalCalories: '1.681',
      totalProtein: '40g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Türlü', '445', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Şam Tatlısı', '517', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    9: DailyMenu(
      dateText: '9 Ağustos Pazar',
      breakfast: ['Şehriye Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Zy.Taze Fasulye', 'Fırın Soğan', 'Turşu'],
      totalCalories: '1.461',
      totalProtein: '57g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Yoğ.Orman Kebabı', '386', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Supangle', '349', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    10: DailyMenu(
      dateText: '10 Ağustos Pazartesi',
      breakfast: ['Ezogelin Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Pancar Turşusu', 'Yoğ.Kabak', 'Havuç Rende', 'Salatalık Söğüş'],
      totalCalories: '1.235',
      totalProtein: '47g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Çökertme Kebabı', '431', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    11: DailyMenu(
      dateText: '11 Ağustos Salı',
      breakfast: ['Yayla Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Simit', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Ayranaşı', 'Domates Söğüş', 'Biber Söğüş'],
      totalCalories: '1.277',
      totalProtein: '48g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Piliç Fırın', '451', '28g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    12: DailyMenu(
      dateText: '12 Ağustos Çarşamba',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Patates Kızartması', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Çoban Salata', 'Havuç Tarator', 'Marineli Kırmızı Lahana', 'Turşu'],
      totalCalories: '1.248',
      totalProtein: '44g',
      mainCourse: [MealItem('Yayla Çorba', '234', '7g'), MealItem('Gemici Kuru Fasulye', '363', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    13: DailyMenu(
      dateText: '13 Ağustos Perşembe',
      breakfast: ['Ezogelin Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Domates Söğüş', 'Aysberg', 'Soğan Piyazı', 'Kornişon Turşu'],
      totalCalories: '1.363',
      totalProtein: '41g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Hamburger', '530', '24g'), MealItem('Patates Kızartması', '312', '3g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    14: DailyMenu(
      dateText: '14 Ağustos Cuma',
      breakfast: ['Şehriye Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Kavun', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Yoğ.Makarna', 'Kısır', 'Aysberg', 'Salatalık Söğüş'],
      totalCalories: '1.603',
      totalProtein: '40g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Bezelye', '342', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Baklava', '542', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    15: DailyMenu(
      dateText: '15 Ağustos Cumartesi',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Pembe Sultan', 'Biber Söğüş', 'Domates Söğüş'],
      totalCalories: '1.229',
      totalProtein: '49g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Çoban Kavurma', '432', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '7g')],
    ),
    16: DailyMenu(
      dateText: '16 Ağustos Pazar',
      breakfast: ['Ezogelin Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Fırın Patates', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Ayranaşı', 'Humus', 'Havuç Rende', 'Turşu'],
      totalCalories: '1.485',
      totalProtein: '53g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Mitide Köfte', '445', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Muhallebili Tel Kadayıf', '314', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    17: DailyMenu(
      dateText: '17 Ağustos Pazartesi',
      breakfast: ['Yayla Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Rus Salatası', 'Domates Söğüş', 'Fırın Biber'],
      totalCalories: '1.269',
      totalProtein: '50g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Fırınağzı', '443', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    18: DailyMenu(
      dateText: '18 Ağustos Salı',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Fırın Mücver', 'Yoğ.Semizotu', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.511',
      totalProtein: '41g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Kıbrıs Tatlısı', '425', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    19: DailyMenu(
      dateText: '19 Ağustos Çarşamba',
      breakfast: ['Ezogelin Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Omlet', 'Karpuz', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Zy.Taze Fasulye', 'Marineli Beyaz Lahana', 'Salatalık Söğüş'],
      totalCalories: '1.321',
      totalProtein: '51g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Piliç Izgara', '388', '28g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    20: DailyMenu(
      dateText: '20 Ağustos Perşembe',
      breakfast: ['Şehriye Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Pizza', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Cacık', 'Kısır', 'Aysberg', 'Biber Söğüş'],
      totalCalories: '1.507',
      totalProtein: '42g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Patlıcan Musakka', '412', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Aşure', '376', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    21: DailyMenu(
      dateText: '21 Ağustos Cuma',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Çoban Salata', 'Ayranaşı', 'Havuç Rende', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.247',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '234', '7g'), MealItem('Kasap Köfte', '455', '26g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '81', '5g')],
    ),
    22: DailyMenu(
      dateText: '22 Ağustos Cumartesi',
      breakfast: ['Domates Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Yoğ.Makarna', 'Sebze Buketi', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.402',
      totalProtein: '42g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Etli Kuru Fasulye', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Tiramisu', '316', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    23: DailyMenu(
      dateText: '23 Ağustos Pazar',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Yoğ.Kabak', 'Domates Söğüş', 'Salatalık Söğüş'],
      totalCalories: '1.284',
      totalProtein: '50g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Piliç Baget', '451', '28g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '88', '7g')],
    ),
    24: DailyMenu(
      dateText: '24 Ağustos Pazartesi',
      breakfast: ['Şehriye Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Patates Kızartması', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Cacık', 'Humus', 'Biber Söğüş', 'Marineli Beyaz Lahana'],
      totalCalories: '1.373',
      totalProtein: '56g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Patlıcan Güveç', '412', '15g'), MealItem('Nohutlu Pirinç/Nohutlu Bulgur Pilavı', '370', '20g'), MealItem('Sütlaç', '242', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    25: DailyMenu(
      dateText: '25 Ağustos Salı',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Zy.Mantar', 'Sumaklı Soğan', 'Turşu'],
      totalCalories: '1.283',
      totalProtein: '50g',
      mainCourse: [MealItem('Tutmaç Çorbası', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    26: DailyMenu(
      dateText: '26 Ağustos Çarşamba',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Pancar Turşusu', 'Zy.Ispanak', 'Domates Söğüş', 'Havuç Rende'],
      totalCalories: '1.440',
      totalProtein: '48g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Terbiyeli Köfte', '416', '26g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Mozaik Pasta', '327', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    27: DailyMenu(
      dateText: '27 Ağustos Perşembe',
      breakfast: ['Domates Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Yoğ.Semizotu', 'Fırın Biber', 'Fırın Soğan'],
      totalCalories: '',
      totalProtein: '49g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Piliç Izgara', '388', '28g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '81', '5g')],
    ),
    28: DailyMenu(
      dateText: '28 Ağustos Cuma',
      breakfast: ['Şehriye Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Karpuz', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Yoğ.Makarna', 'Kısır', 'Aysberg', 'Turşu'],
      totalCalories: '1.548',
      totalProtein: '40g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Patates', '450', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Turunç Tatlısı', '372', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    29: DailyMenu(
      dateText: '29 Ağustos Cumartesi',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Çoban Salata', 'Ayranaşı', 'Fırın Soğan', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.247',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '234', '7g'), MealItem('Kayseri Köfte', '455', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    30: DailyMenu(
      dateText: '30 Ağustos Pazar',
      breakfast: ['Domates Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Cacık', 'Mevsim Salata', 'Biber Söğüş', 'Domates Söğüş'],
      totalCalories: '1.672',
      totalProtein: '40g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Karnıyarık', '451', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Yoğurt Tatlısı', '524', '7g'), MealItem('Yoğurt', '81', '7g')],
    ),
    31: DailyMenu(
      dateText: '31 Ağustos Pazartesi',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Rus Salatası', 'Fırın Mücver', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.306',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
  };

  static final Map<int, DailyMenu> septemberMenu = {
    1: DailyMenu(
      dateText: '1 Eylül Salı',
      breakfast: ['Şehriye Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Ispanaklı Kol Böreği', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Anadolu Çorba', '300', '10g'), MealItem('Çökertme Kebabı', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    2: DailyMenu(
      dateText: '2 Eylül Çarşamba',
      breakfast: ['Ezogelin Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Sucuklu Yumurta', 'Patates Kızartması', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Mitide Köfte', '300', '10g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '300', '10g'), MealItem('Browni', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    3: DailyMenu(
      dateText: '3 Eylül Perşembe',
      breakfast: ['Yayla Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Simit', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Sebzeli Tavuk Kebabı', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    4: DailyMenu(
      dateText: '4 Eylül Cuma',
      breakfast: ['Mercimek Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Etli Patates', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Sütlaç', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    5: DailyMenu(
      dateText: '5 Eylül Cumartesi',
      breakfast: ['Şehriye Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '300', '10g'), MealItem('İzmir Köfte', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    6: DailyMenu(
      dateText: '6 Eylül Pazar',
      breakfast: ['Ezogelin Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Etli Biber Dolma', '300', '10g'), MealItem('Barbunya Pilaki', '300', '10g'), MealItem('Komposto', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    7: DailyMenu(
      dateText: '7 Eylül Pazartesi',
      breakfast: ['Domates Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Etli Kuru Fasulye', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Kıbrıs Tatlısı', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    8: DailyMenu(
      dateText: '8 Eylül Salı',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Tutmaç Çorbası', '300', '10g'), MealItem('Et Döner', '300', '10g'), MealItem('Pirinç Pilavı', '300', '10g'), MealItem('Dondurma', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    9: DailyMenu(
      dateText: '9 Eylül Çarşamba',
      breakfast: ['Şehriye Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Üzümlü Kek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Piliç Izgara', '300', '10g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    10: DailyMenu(
      dateText: '10 Eylül Perşembe',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Menemen', 'Karpuz', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Etli Türlü', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Turunç Tatlısı', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    11: DailyMenu(
      dateText: '11 Eylül Cuma',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Terbiyeli Köfte', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    12: DailyMenu(
      dateText: '12 Eylül Cumartesi',
      breakfast: ['Yayla Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Etli Bezelye', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Tiramisu', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    13: DailyMenu(
      dateText: '13 Eylül Pazar',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Simit', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '300', '10g'), MealItem('Mantarlı Tavuk Sote', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Supangle', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    14: DailyMenu(
      dateText: '14 Eylül Pazartesi',
      breakfast: ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Sucuklu Yumurta', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Fırınağzı', '300', '10g'), MealItem('Seb.Pirinç/Seb.Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    15: DailyMenu(
      dateText: '15 Eylül Salı',
      breakfast: ['Şehriye Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Gemici Kuru Fasulye', '300', '10g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '300', '10g'), MealItem('Mozaik Pasta', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    16: DailyMenu(
      dateText: '16 Eylül Çarşamba',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Kasap Köfte', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Dondurma', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    17: DailyMenu(
      dateText: '17 Eylül Perşembe',
      breakfast: ['Yayla Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '300', '10g'), MealItem('Etli Taze Fasulye', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Şam Tatlı', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    18: DailyMenu(
      dateText: '18 Eylül Cuma',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'Menemen', 'Karpuz', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Piliç Fırın', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    19: DailyMenu(
      dateText: '19 Eylül Cumartesi',
      breakfast: ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Karnıyarık', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Muhallebili Tel Kadayıf', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    20: DailyMenu(
      dateText: '20 Eylül Pazar',
      breakfast: ['Domates Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Yöğ. Orman Kebabı', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    21: DailyMenu(
      dateText: '21 Eylül Pazartesi',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Etli Nohut Yahni', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    22: DailyMenu(
      dateText: '22 Eylül Salı',
      breakfast: ['Şehriye Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Sucuklu Yumurta', 'Patates Kızartması', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Hamburger', '300', '10g'), MealItem('Patates Kızartması', '300', '10g'), MealItem('Dondurma', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    23: DailyMenu(
      dateText: '23 Eylül Çarşamba',
      breakfast: ['Ezogelin Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Patlıcan Musakka', '300', '10g'), MealItem('Noh.Pirinç/Noh.Bulgur Pilavı', '300', '10g'), MealItem('Baklava', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    24: DailyMenu(
      dateText: '24 Eylül Perşembe',
      breakfast: ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Piliç Izgara', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    25: DailyMenu(
      dateText: '25 Eylül Cuma',
      breakfast: ['Yayla Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Pizza', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '300', '10g'), MealItem('Püreli Rosto Köfte', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Aşure', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    26: DailyMenu(
      dateText: '26 Eylül Cumartesi',
      breakfast: ['Ezogelin Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Etli Kuru Fasulye', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Yoğurt Tatlısı', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    27: DailyMenu(
      dateText: '27 Eylül Pazar',
      breakfast: ['Şehriye Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Taş Kebap', '300', '10g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '300', '10g'), MealItem('Meyve', '300', '10g'), MealItem('Ayran', '300', '10g')],
    ),
    28: DailyMenu(
      dateText: '28 Eylül Pazartesi',
      breakfast: ['Mercimek Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '300', '10g'), MealItem('Patlıcan Güveç', '300', '10g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '300', '10g'), MealItem('Sütlaç', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
    29: DailyMenu(
      dateText: '29 Eylül Salı',
      breakfast: ['Ezogelin Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '300', '10g'), MealItem('Fırın Balık', '300', '10g'), MealItem('Barbunya Pilaki', '300', '10g'), MealItem('İrmik Helva', '300', '10g'), MealItem('Şalgam', '300', '10g')],
    ),
    30: DailyMenu(
      dateText: '30 Eylül Çarşamba',
      breakfast: ['Yayla Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'Menemen', 'Patates Kızartması', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: ['Mevsim Salata', 'Cacık', 'Turşu', 'Söğüş'],
      totalCalories: '1.450',
      totalProtein: '45g',
      mainCourse: [MealItem('Ezogelin Çorba', '300', '10g'), MealItem('Etli Nohut Yahni', '300', '10g'), MealItem('Pirinç/Bulgur Pilavı', '300', '10g'), MealItem('Dondurma', '300', '10g'), MealItem('Yoğurt', '300', '10g')],
    ),
  };

  static final Map<int, DailyMenu> octoberMenu = {
    1: DailyMenu(
      dateText: '1 Ekim Perşembe',
      breakfast: ['Mercimek Çorba','Kaşar Peynir','Siyah Zeytin','Tahin Pekmez','H.Yumurta','Biberli Ekmek','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Mevsim Salata','Pancar Turşusu','Domates Söğüş','Fırın Soğan'],
      totalCalories: '1.243',
      totalProtein: '51g',
      mainCourse: [MealItem('Yayla Çorba', '234', '8g'), MealItem('Piliç Fırın', '451', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    2: DailyMenu(
      dateText: '2 Ekim Cuma',
      breakfast: ['Ezogelin Çorba','Beyaz Peynir','Biberli Zeytin','Bal','Omlet','Domates-Salatalık','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Çoban Salata','Ayranaşı','Havuç Rende','Turşu'],
      totalCalories: '1.778',
      totalProtein: '55g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Et Kavurma', '468', '30g'), MealItem('İç Pilav', '412', '6g'), MealItem('Baklava', '542', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    3: DailyMenu(
      dateText: '3 Ekim Cumartesi',
      breakfast: ['Şehriye Çorba','Krem Peynir','Siyah Zeytin','Reçel','H.Yumurta','Üzümlü Kek','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Yoğ.Makarna','Humus','Biber Söğüş','Marineli Kırmızı Lahana'],
      totalCalories: '1.555',
      totalProtein: '33g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Kabak Kalye', '340', '8g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Tulumba Tatlısı', '496', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    4: DailyMenu(
      dateText: '4 Ekim Pazar',
      breakfast: ['Yayla Çorba','Kaşar Peynir','Yeşil Zeytin','Fındık Ezmesi','Menemen','Fırın Patates','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Cacık','Mevsim Salata','Domates Söğüş','Turşu'],
      totalCalories: '1.248',
      totalProtein: '41g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Karnıyarık', '451', '20g'), MealItem('Noh.Pirinç/Noh.Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '6g')],
    ),
    5: DailyMenu(
      dateText: '5 Ekim Pazartesi',
      breakfast: ['Mercimek Çorba','Beyaz Peynir','Siyah Zeytin','Tahin Pekmez','H.Yumurta','Ispanaklı Kol Böreği','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Rus Salatası','Sebze Buketi','Biber Söğüş','Marineli Beyaz Lahana'],
      totalCalories: '1.591',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '234', '8g'), MealItem('Etli Kuru Fasulye', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Şam Tatlı', '517', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    6: DailyMenu(
      dateText: '6 Ekim Salı',
      breakfast: ['Ezogelin Çorba','Krem Peynir','Biberli Zeytin','Bal','Sucuklu Yumurta','Domates-Salatalık','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Mevsim Salata','Fırın Patates','Sumaklı Soğan','Turşu'],
      totalCalories: '1.283',
      totalProtein: '51g',
      mainCourse: [MealItem('Tutmaç Çorbası', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    7: DailyMenu(
      dateText: '7 Ekim Çarşamba',
      breakfast: ['Şehriye Çorba','Kaşar Peynir','Siyah Zeytin','Reçel','H.Yumurta','Poğaça','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Karışık Kızartma','Kısır','Aysberg','Domates Söğüş'],
      totalCalories: '1.549',
      totalProtein: '43g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Zy.Ispanak', '324', '10g'), MealItem('Kıymalı Börek', '513', '14g'), MealItem('Browni', '349', '5g'), MealItem('Ayran', '88', '6g')],
    ),
    8: DailyMenu(
      dateText: '8 Ekim Perşembe',
      breakfast: ['Domates Çorba','Beyaz Peynir','Biberli Zeytin','Fındık Ezmesi','Omlet','Patates Kızartması','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Mevsim Salata','Pembe Sultan','Salatalık Söğüş','Biber Söğüş'],
      totalCalories: '1.408',
      totalProtein: '59g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Püreli Kadınbudu Köfte', '643', '30g'), MealItem('Zy.Taze Fasulye', '331', '14g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    9: DailyMenu(
      dateText: '9 Ekim Cuma',
      breakfast: ['Mercimek Çorba','Krem Peynir','Siyah Zeytin','Tahin Pekmez','H.Yumurta','Simit','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Acılı Kaşık Salata','Yoğ.Semizotu','Havuç Rende','Marineli Kırmızı Lahana'],
      totalCalories: '1.214',
      totalProtein: '51g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Piliç Izgara', '388', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    10: DailyMenu(
      dateText: '10 Ekim Cumartesi',
      breakfast: ['Şehriye Çorba','Kaşar Peynir','Yeşil Zeytin','Bal','Menemen','Fırın Patates','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Mevsim Salata','Yoğ.Biber','Soğan Söğüş','Turşu'],
      totalCalories: '1.499',
      totalProtein: '45g',
      mainCourse: [MealItem('Yayla Çorba', '234', '8g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Kıbrıs Tatlısı', '425', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    11: DailyMenu(
      dateText: '11 Ekim Pazar',
      breakfast: ['Ezogelin Çorba','Beyaz Peynir','Siyah Zeytin','Reçel','H.Yumurta','Havuçlu Kek','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Fırın Mücver','Yoğ.Patlıcan','Biber Söğüş','Domates Söğüş'],
      totalCalories: '1.281',
      totalProtein: '51g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Tas Kebap', '455', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '6g')],
    ),
    12: DailyMenu(
      dateText: '12 Ekim Pazartesi',
      breakfast: ['Yayla Çorba','Krem Peynir','Biberli Zeytin','Fındık Ezmesi','Omlet','Domates-Salatalık','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Roka Salatası','Fırın Patates','Soğan Söğüş','Turşu'],
      totalCalories: '1.580',
      totalProtein: '58g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Fırın Balık', '410', '30g'), MealItem('Barbunya Pilaki', '363', '14g'), MealItem('İrmik Helva', '469', '5g'), MealItem('Şalgam', '70', '1g')],
    ),
    13: DailyMenu(
      dateText: '13 Ekim Salı',
      breakfast: ['Mercimek Çorba','Kaşar Peynir','Siyah Zeytin','Tahin Pekmez','H.Yumurta','Pizza','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Cacık','Humus','Biber Söğüş','Havuç Rende'],
      totalCalories: '1.209',
      totalProtein: '41g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Patlıcan Güveç', '412', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '6g')],
    ),
    14: DailyMenu(
      dateText: '14 Ekim Çarşamba',
      breakfast: ['Ezogelin Çorba','Beyaz Peynir','Biberli Zeytin','Bal','Sucuklu Yumurta','Fırın Patates','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Çoban Salata','Rus Salatası','Marineli Kırmızı Lahana','Turşu'],
      totalCalories: '1.364',
      totalProtein: '39g',
      mainCourse: [MealItem('Yayla Çorba', '234', '8g'), MealItem('Gemici Kuru Fasulye', '363', '14g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Tiramisu', '316', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    15: DailyMenu(
      dateText: '15 Ekim Perşembe',
      breakfast: ['Şehriye Çorba','Krem Peynir','Siyah Zeytin','Reçel','H.Yumurta','Peynirli Kol Böreği','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Domates Söğüş','Aysberg','Soğan Piyazı','Kornişon Turşu'],
      totalCalories: '1.305',
      totalProtein: '33g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Hamburger', '530', '10g'), MealItem('Patates Kızartması', '312', '8g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    16: DailyMenu(
      dateText: '16 Ekim Cuma',
      breakfast: ['Yayla Çorba','Kaşar Peynir','Yeşil Zeytin','Fındık Ezmesi','Menemen','Fırın Patates','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Yoğ.Makarna','Kısır','Biber Söğüş','Havuç Rende'],
      totalCalories: '1.585',
      totalProtein: '46g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Bezelye', '342', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Yoğurt Tatlısı', '524', '6g'), MealItem('Yoğurt', '81', '6g')],
    ),
    17: DailyMenu(
      dateText: '17 Ekim Cumartesi',
      breakfast: ['Mercimek Çorba','Beyaz Peynir','Siyah Zeytin','Tahin Pekmez','H.Yumurta','Zeytinli Açma','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Mevsim Salata','Yoğ.Kabak','Domates Söğüş','Salatalık Söğüş'],
      totalCalories: '1.314',
      totalProtein: '51g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Püreli Rosto Köfte', '510', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    18: DailyMenu(
      dateText: '18 Ekim Pazar',
      breakfast: ['Ezogelin Çorba','Krem Peynir','Biberli Zeytin','Bal','Omlet','Domates-Salatalık','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Yoğ.Kereviz','Pancarlı Şehriye Salatası','Marineli Beyaz Lahana','Fırın Biber'],
      totalCalories: '1.521',
      totalProtein: '55g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Mantarlı Tavuk Sote', '446', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Supangle', '349', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    19: DailyMenu(
      dateText: '19 Ekim Pazartesi',
      breakfast: ['Şehriye Çorba','Kaşar Peynir','Siyah Zeytin','Reçel','Menemen','Fırın Patates','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Mütebbel','Mevsim Salata','Soğan Söğüş','Turşu'],
      totalCalories: '1.228',
      totalProtein: '41g',
      mainCourse: [MealItem('Yayla Çorba', '234', '8g'), MealItem('Etli Nohut Yahni', '443', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '6g')],
    ),
    20: DailyMenu(
      dateText: '20 Ekim Salı',
      breakfast: ['Mercimek Çorba','Beyaz Peynir','Biberli Zeytin','Fındık Ezmesi','H.Yumurta','Simit','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Ayranaşı','Fırın Mücver','Domates Söğüş','Biber Söğüş'],
      totalCalories: '1.622',
      totalProtein: '63g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Mitide Köfte', '445', '30g'), MealItem('Fırın Makarna', '494', '14g'), MealItem('Mozaik Pasta', '327', '5g'), MealItem('Ayran', '88', '6g')],
    ),
    21: DailyMenu(
      dateText: '21 Ekim Çarşamba',
      breakfast: ['Domates Çorba','Krem Peynir','Siyah Zeytin','Tahin Pekmez','Omlet','Domates-Salatalık','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Mevsim Salata','Fırın Karnabahar','Sumaklı Soğan','Turşu'],
      totalCalories: '1.283',
      totalProtein: '51g',
      mainCourse: [MealItem('Anadolu Çorba', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    22: DailyMenu(
      dateText: '22 Ekim Perşembe',
      breakfast: ['Ezogelin Çorba','Kaşar Peynir','Yeşil Zeytin','Bal','H.Yumurta','Havuçlu Kek','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Yoğ.Makarna','Kısır','Aysberg','Havuç Rende'],
      totalCalories: '1.519',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Etli Patates', '450', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Turunç Tatlısı', '372', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    23: DailyMenu(
      dateText: '23 Ekim Cuma',
      breakfast: ['Yayla Çorba','Beyaz Peynir','Siyah Zeytin','Reçel','Menemen','Patates Kızartması','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Mevsim Salata','Zy.Kereviz','Biber Söğüş','Fırın Soğan'],
      totalCalories: '1.466',
      totalProtein: '59g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Piliç Topkapı', '640', '30g'), MealItem('Barbunya Pilaki', '363', '14g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    24: DailyMenu(
      dateText: '24 Ekim Cumartesi',
      breakfast: ['Şehriye Çorba','Krem Peynir','Biberli Zeytin','Fındık Ezmesi','H.Yumurta','Poğaça','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Ayranaşı','Humus','Domates Söğüş','Marineli Kırmızı Lahana'],
      totalCalories: '1.478',
      totalProtein: '50g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Türlü', '445', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Muhallebili Tel Kadayıf', '314', '10g'), MealItem('Yoğurt', '81', '6g')],
    ),
    25: DailyMenu(
      dateText: '25 Ekim Pazar',
      breakfast: ['Mercimek Çorba','Kaşar Peynir','Siyah Zeytin','Tahin Pekmez','Omlet','Domates-Salatalık','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Çoban Salata','Sebze Buketi','Havuç Rende','Turşu'],
      totalCalories: '1.250',
      totalProtein: '51g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('İzmir Köfte', '453', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '6g')],
    ),
    26: DailyMenu(
      dateText: '26 Ekim Pazartesi',
      breakfast: ['Ezogelin Çorba','Beyaz Peynir','Biberli Zeytin','Bal','H.Yumurta','Peynirli Kol Böreği','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Yoğ.Semizotu','Pancar Turşusu','Biber Söğüş','Salatalık Söğüş'],
      totalCalories: '1.419',
      totalProtein: '51g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Et Haşlama', '586', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    27: DailyMenu(
      dateText: '27 Ekim Salı',
      breakfast: ['Şehriye Çorba','Krem Peynir','Siyah Zeytin','Reçel','Sucuklu Yumurta','Domates-Salatalık','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Şakşuka','Kısır','Aysberg','Turşu'],
      totalCalories: '1.611',
      totalProtein: '39g',
      mainCourse: [MealItem('Aşçıbaşı Çorba', '287', '8g'), MealItem('Zy.Taze Fasulye', '331', '14g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Baklava', '542', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    28: DailyMenu(
      dateText: '28 Ekim Çarşamba',
      breakfast: ['Mercimek Çorba','Kaşar Peynir','Yeşil Zeytin','Fındık Ezmesi','H.Yumurta','Biberli Ekmek','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Mevsim Salata','Zy.Ispanak','Biber Söğüş','Domates Söğüş'],
      totalCalories: '1.242',
      totalProtein: '51g',
      mainCourse: [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Terbiyeli Köfte', '416', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    29: DailyMenu(
      dateText: '29 Ekim Perşembe',
      breakfast: ['Yayla Çorba','Beyaz Peynir','Siyah Zeytin','Tahin Pekmez','Menemen','Fırın Patates','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Patates Sote','Havuç Tarator','Soğan Söğüş','Turşu'],
      totalCalories: '1.328',
      totalProtein: '45g',
      mainCourse: [MealItem('Şehriye Çorba', '246', '8g'), MealItem('Etli Kuru Fasulye', '389', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '6g'), MealItem('Sütlaç', '242', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
    30: DailyMenu(
      dateText: '30 Ekim Cuma',
      breakfast: ['Ezogelin Çorba','Krem Peynir','Biberli Zeytin','Bal','H.Yumurta','Zeytinli Açma','Tereyağı','Meyve Suyu','Çay/Ekmek'],
      salad: ['Mevsim Salata','Rus Salatası','Marineli Beyaz Lahana','Salatalık Söğüş'],
      totalCalories: '1.252',
      totalProtein: '51g',
      mainCourse: [MealItem('Tutmaç Çorbası', '269', '8g'), MealItem('Sebzeli Tavuk Kebabı', '425', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '6g')],
    ),
    31: DailyMenu(
      dateText: '31 Ekim Cumartesi',
      breakfast: ['Şehriye Çorba','Kaşar Peynir','Siyah Zeytin','Reçel','Omlet','Domates-Salatalık','Tereyağı','Süt','Çay/Ekmek'],
      salad: ['Cacık','Humus','Havuç Rende','Domates Söğüş'],
      totalCalories: '1.514',
      totalProtein: '45g',
      mainCourse: [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Patlıcan Musakka', '412', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Aşure', '376', '5g'), MealItem('Yoğurt', '81', '6g')],
    ),
  };
}
