class MealItem {
  final String name;
  final String calories;
  final String protein;
  const MealItem(this.name, [this.calories = '', this.protein = '']);
}

class DailyMenu {
  final String dateText;
  final List<String> breakfast;
  final List<String> salad;
  final List<MealItem> mainCourse;
  final String totalCalories;
  final String totalProtein;
  const DailyMenu({required this.dateText, required this.breakfast, required this.salad, required this.mainCourse, required this.totalCalories, this.totalProtein = ''});
}

class MenuData {
  static const Map<int, DailyMenu> augustMenu = {
    1: DailyMenu(
      dateText: '1 Ağustos Cumartesi',
      breakfast: const ['Şehriye Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Ayranaşı', 'Kısır', 'Aysberg', 'Marineli Beyaz Lahana'],
      totalCalories: '1.514',
      totalProtein: '38g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Patates Musakka', '468', '15g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Browni', '349', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    2: DailyMenu(
      dateText: '2 Ağustos Pazar',
      breakfast: const ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Cacık', 'Humus', 'Domates Söğüş', 'Havuç Rende'],
      totalCalories: '1.403',
      totalProtein: '45g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Biber Dolma', '461', '15g'), MealItem('Barbunya Pilaki', '363', '14g'), MealItem('Komposto', '223', '1g'), MealItem('Yoğurt', '81', '7g')],
    ),
    3: DailyMenu(
      dateText: '3 Ağustos Pazartesi',
      breakfast: const ['Yayla Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Ispanaklı Kol Böreği', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Fırın Patates', 'Sumaklı Soğan', 'Turşu'],
      totalCalories: '1.383',
      totalProtein: '53g',
      mainCourse: const [MealItem('Anadolu Çorba', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    4: DailyMenu(
      dateText: '4 Ağustos Salı',
      breakfast: const ['Mercimek Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Karpuz', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Yoğ.Makarna', 'Fırın Mücver', 'Biber Söğüş', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.617',
      totalProtein: '43g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Taze Fasulye', '374', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Yoğurt Tatlısı', '524', '7g'), MealItem('Yoğurt', '81', '7g')],
    ),
    5: DailyMenu(
      dateText: '5 Ağustos Çarşamba',
      breakfast: const ['Şehriye Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Pancarlı Şehriye Salatası', 'Domates Söğüş', 'Salatalık Söğüş'],
      totalCalories: '1.217',
      totalProtein: '49g',
      mainCourse: const [MealItem('Yayla Çorba', '234', '7g'), MealItem('Sebzeli Tavuk Kebabı', '425', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    6: DailyMenu(
      dateText: '6 Ağustos Perşembe',
      breakfast: const ['Ezogelin Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Çoban Salata', 'Yoğ.Patlıcan', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.357',
      totalProtein: '48g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Sütlaç', '242', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    7: DailyMenu(
      dateText: '7 Ağustos Cuma',
      breakfast: const ['Domates Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'H.Yumurta', 'Üzümlü Kek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Rus Salatası', 'Fırın Biber', 'Marineli Beyaz Lahana'],
      totalCalories: '1.245',
      totalProtein: '43g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Hasanpaşa Köfte', '441', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    8: DailyMenu(
      dateText: '8 Ağustos Cumartesi',
      breakfast: const ['Mercimek Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Cacık', 'Kısır', 'Aysberg', 'Domates Söğüş'],
      totalCalories: '1.681',
      totalProtein: '40g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Türlü', '445', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Şam Tatlısı', '517', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    9: DailyMenu(
      dateText: '9 Ağustos Pazar',
      breakfast: const ['Şehriye Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Zy.Taze Fasulye', 'Fırın Soğan', 'Turşu'],
      totalCalories: '1.461',
      totalProtein: '57g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Yoğ.Orman Kebabı', '386', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Supangle', '349', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    10: DailyMenu(
      dateText: '10 Ağustos Pazartesi',
      breakfast: const ['Ezogelin Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Pancar Turşusu', 'Yoğ.Kabak', 'Havuç Rende', 'Salatalık Söğüş'],
      totalCalories: '1.235',
      totalProtein: '47g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Çökertme Kebabı', '431', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    11: DailyMenu(
      dateText: '11 Ağustos Salı',
      breakfast: const ['Yayla Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Simit', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Ayranaşı', 'Domates Söğüş', 'Biber Söğüş'],
      totalCalories: '1.277',
      totalProtein: '48g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Piliç Fırın', '451', '28g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    12: DailyMenu(
      dateText: '12 Ağustos Çarşamba',
      breakfast: const ['Mercimek Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Patates Kızartması', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Çoban Salata', 'Havuç Tarator', 'Marineli Kırmızı Lahana', 'Turşu'],
      totalCalories: '1.248',
      totalProtein: '44g',
      mainCourse: const [MealItem('Yayla Çorba', '234', '7g'), MealItem('Gemici Kuru Fasulye', '363', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    13: DailyMenu(
      dateText: '13 Ağustos Perşembe',
      breakfast: const ['Ezogelin Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Domates Söğüş', 'Aysberg', 'Soğan Piyazı', 'Kornişon Turşu'],
      totalCalories: '1.363',
      totalProtein: '41g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Hamburger', '530', '24g'), MealItem('Patates Kızartması', '312', '3g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    14: DailyMenu(
      dateText: '14 Ağustos Cuma',
      breakfast: const ['Şehriye Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Kavun', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Yoğ.Makarna', 'Kısır', 'Aysberg', 'Salatalık Söğüş'],
      totalCalories: '1.603',
      totalProtein: '40g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Bezelye', '342', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Baklava', '542', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    15: DailyMenu(
      dateText: '15 Ağustos Cumartesi',
      breakfast: const ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Poğaça', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Pembe Sultan', 'Biber Söğüş', 'Domates Söğüş'],
      totalCalories: '1.229',
      totalProtein: '49g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Çoban Kavurma', '432', '30g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '81', '7g')],
    ),
    16: DailyMenu(
      dateText: '16 Ağustos Pazar',
      breakfast: const ['Ezogelin Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Fırın Patates', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Ayranaşı', 'Humus', 'Havuç Rende', 'Turşu'],
      totalCalories: '1.485',
      totalProtein: '53g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Mitide Köfte', '445', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Muhallebili Tel Kadayıf', '314', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    17: DailyMenu(
      dateText: '17 Ağustos Pazartesi',
      breakfast: const ['Yayla Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Rus Salatası', 'Domates Söğüş', 'Fırın Biber'],
      totalCalories: '1.269',
      totalProtein: '50g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Fırınağzı', '443', '30g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    18: DailyMenu(
      dateText: '18 Ağustos Salı',
      breakfast: const ['Mercimek Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Fırın Mücver', 'Yoğ.Semizotu', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.511',
      totalProtein: '41g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Kıbrıs Tatlısı', '425', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    19: DailyMenu(
      dateText: '19 Ağustos Çarşamba',
      breakfast: const ['Ezogelin Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Omlet', 'Karpuz', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Zy.Taze Fasulye', 'Marineli Beyaz Lahana', 'Salatalık Söğüş'],
      totalCalories: '1.321',
      totalProtein: '51g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Piliç Izgara', '388', '28g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Ayran', '88', '5g')],
    ),
    20: DailyMenu(
      dateText: '20 Ağustos Perşembe',
      breakfast: const ['Şehriye Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Reçel', 'H.Yumurta', 'Pizza', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Cacık', 'Kısır', 'Aysberg', 'Biber Söğüş'],
      totalCalories: '1.507',
      totalProtein: '42g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Patlıcan Musakka', '412', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Aşure', '376', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    21: DailyMenu(
      dateText: '21 Ağustos Cuma',
      breakfast: const ['Mercimek Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Çoban Salata', 'Ayranaşı', 'Havuç Rende', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.247',
      totalProtein: '45g',
      mainCourse: const [MealItem('Yayla Çorba', '234', '7g'), MealItem('Kasap Köfte', '455', '26g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '81', '5g')],
    ),
    22: DailyMenu(
      dateText: '22 Ağustos Cumartesi',
      breakfast: const ['Domates Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Peynirli Kol Böreği', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Yoğ.Makarna', 'Sebze Buketi', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.402',
      totalProtein: '42g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Etli Kuru Fasulye', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Tiramisu', '316', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    23: DailyMenu(
      dateText: '23 Ağustos Pazar',
      breakfast: const ['Ezogelin Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Bal', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Yoğ.Kabak', 'Domates Söğüş', 'Salatalık Söğüş'],
      totalCalories: '1.284',
      totalProtein: '50g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Piliç Baget', '451', '28g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Yoğurt', '88', '7g')],
    ),
    24: DailyMenu(
      dateText: '24 Ağustos Pazartesi',
      breakfast: const ['Şehriye Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Reçel', 'Sucuklu Yumurta', 'Patates Kızartması', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Cacık', 'Humus', 'Biber Söğüş', 'Marineli Beyaz Lahana'],
      totalCalories: '1.373',
      totalProtein: '56g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Patlıcan Güveç', '412', '15g'), MealItem('Nohutlu Pirinç/Nohutlu Bulgur Pilavı', '370', '20g'), MealItem('Sütlaç', '242', '6g'), MealItem('Yoğurt', '81', '7g')],
    ),
    25: DailyMenu(
      dateText: '25 Ağustos Salı',
      breakfast: const ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Zeytinli Açma', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Zy.Mantar', 'Sumaklı Soğan', 'Turşu'],
      totalCalories: '1.283',
      totalProtein: '50g',
      mainCourse: const [MealItem('Tutmaç Çorbası', '269', '8g'), MealItem('Et Döner', '432', '30g'), MealItem('Pirinç Pilavı', '394', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    26: DailyMenu(
      dateText: '26 Ağustos Çarşamba',
      breakfast: const ['Ezogelin Çorba', 'Kaşar Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'Omlet', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Pancar Turşusu', 'Zy.Ispanak', 'Domates Söğüş', 'Havuç Rende'],
      totalCalories: '1.440',
      totalProtein: '48g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Terbiyeli Köfte', '416', '26g'), MealItem('Pirinç/Soslu Bulgur Pilavı', '370', '6g'), MealItem('Mozaik Pasta', '327', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    27: DailyMenu(
      dateText: '27 Ağustos Perşembe',
      breakfast: const ['Domates Çorba', 'Beyaz Peynir', 'Biberli Zeytin', 'Bal', 'H.Yumurta', 'Biberli Ekmek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Mevsim Salata', 'Yoğ.Semizotu', 'Fırın Biber', 'Fırın Soğan'],
      totalCalories: '',
      totalProtein: '49g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Piliç Izgara', '388', '28g'), MealItem('Pirinç/Esmer Bulgur Pilavı', '370', '7g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '81', '5g')],
    ),
    28: DailyMenu(
      dateText: '28 Ağustos Cuma',
      breakfast: const ['Şehriye Çorba', 'Krem Peynir', 'Siyah Zeytin', 'Reçel', 'Menemen', 'Karpuz', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Yoğ.Makarna', 'Kısır', 'Aysberg', 'Turşu'],
      totalCalories: '1.548',
      totalProtein: '40g',
      mainCourse: const [MealItem('Mercimek Çorba', '275', '8g'), MealItem('Etli Patates', '450', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Turunç Tatlısı', '372', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
    29: DailyMenu(
      dateText: '29 Ağustos Cumartesi',
      breakfast: const ['Ezogelin Çorba', 'Kaşar Peynir', 'Biberli Zeytin', 'Fındık Ezmesi', 'H.Yumurta', 'Havuçlu Kek', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Çoban Salata', 'Ayranaşı', 'Fırın Soğan', 'Marineli Kırmızı Lahana'],
      totalCalories: '1.247',
      totalProtein: '45g',
      mainCourse: const [MealItem('Yayla Çorba', '234', '7g'), MealItem('Kayseri Köfte', '455', '26g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Meyve', '100', '1g'), MealItem('Ayran', '88', '5g')],
    ),
    30: DailyMenu(
      dateText: '30 Ağustos Pazar',
      breakfast: const ['Domates Çorba', 'Beyaz Peynir', 'Siyah Zeytin', 'Tahin Pekmez', 'H.Yumurta', 'Domates-Salatalık', 'Tereyağı', 'Süt', 'Çay/Ekmek'],
      salad: const ['Cacık', 'Mevsim Salata', 'Biber Söğüş', 'Domates Söğüş'],
      totalCalories: '1.672',
      totalProtein: '40g',
      mainCourse: const [MealItem('Şehriye Çorba', '246', '5g'), MealItem('Karnıyarık', '451', '15g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Yoğurt Tatlısı', '524', '7g'), MealItem('Yoğurt', '81', '7g')],
    ),
    31: DailyMenu(
      dateText: '31 Ağustos Pazartesi',
      breakfast: const ['Mercimek Çorba', 'Krem Peynir', 'Yeşil Zeytin', 'Bal', 'Menemen', 'Fırın Patates', 'Tereyağı', 'Meyve Suyu', 'Çay/Ekmek'],
      salad: const ['Rus Salatası', 'Fırın Mücver', 'Soğan Söğüş', 'Turşu'],
      totalCalories: '1.306',
      totalProtein: '45g',
      mainCourse: const [MealItem('Ezogelin Çorba', '268', '8g'), MealItem('Etli Nohut Yahni', '389', '20g'), MealItem('Pirinç/Bulgur Pilavı', '370', '6g'), MealItem('Dondurma', '200', '4g'), MealItem('Yoğurt', '81', '7g')],
    ),
  };
}
