class ShipData {
  final String id;
  final String kategori; // 'Rihtimdaki', 'Demirdeki', 'Beklenen'
  final String gemiAdi;
  final String tarihStr;
  final String firmaUlke;
  final String yukCinsi;
  final String islem; // 'Tahliye', 'Yukleme'
  final int miktar; // Ton
  final DateTime sortDate;
  
  // AIS & Canlı Radar Detayları
  final String gemiTipi;
  final String bayrak;
  final String imoNo;
  final String iskeleNo;
  final double progress; // 0.0 - 1.0
  final double lat;
  final double lng;
  final double heading;
  final double speedKnots;
  final String durum;

  const ShipData({
    required this.id,
    required this.kategori,
    required this.gemiAdi,
    required this.tarihStr,
    required this.firmaUlke,
    required this.yukCinsi,
    required this.islem,
    required this.miktar,
    required this.sortDate,
    required this.gemiTipi,
    required this.bayrak,
    required this.imoNo,
    required this.iskeleNo,
    required this.progress,
    required this.lat,
    required this.lng,
    required this.heading,
    required this.speedKnots,
    required this.durum,
  });

  static List<ShipData> getAllShips() {
    return [
      // 1. DIŞ UZUN İSKELEDEKİ GEMİ
      ShipData(
        id: '1',
        kategori: 'Rihtimdaki',
        gemiAdi: 'CHEMICAL EXPLORER',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'Koppers / Singapur',
        yukCinsi: 'Katran / Kimyasal Sıvı',
        islem: 'Yukleme',
        miktar: 11000,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Chemical Tanker',
        bayrak: '🇸🇬 Singapur',
        imoNo: 'IMO 9518290',
        iskeleNo: 'Dış Uzun İskele (Tanker Başı)',
        progress: 0.80,
        lat: 36.7264,
        lng: 36.1863,
        heading: 245.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Yükleme Yapılıyor (%80)',
      ),

      // 2. İÇ RIHTIMLARDAKİ ANA GEMİLER
      ShipData(
        id: '2',
        kategori: 'Rihtimdaki',
        gemiAdi: 'MV IONIC SPIRIT',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'Milpa / Kolombiya',
        yukCinsi: 'Met. Kok Kömürü',
        islem: 'Tahliye',
        miktar: 33000,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Supramax Bulk Carrier',
        bayrak: '🇲🇭 Marshall Adaları',
        imoNo: 'IMO 9514200',
        iskeleNo: '1. Rıhtım (Kuzey İskelesi)',
        progress: 0.65,
        lat: 36.7255,
        lng: 36.1952,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Tahliye Ediliyor (%65)',
      ),
      ShipData(
        id: '3',
        kategori: 'Rihtimdaki',
        gemiAdi: 'GALA A',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'Arel Shipping / Türkiye',
        yukCinsi: 'Genel Kargo / Sac',
        islem: 'Yukleme',
        miktar: 5500,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'General Cargo Ship',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 8822040',
        iskeleNo: 'İç Parmak İskele (Finger Quay)',
        progress: 0.90,
        lat: 36.7248,
        lng: 36.1960,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Yükleme Yapılıyor (%90)',
      ),
      ShipData(
        id: '4',
        kategori: 'Rihtimdaki',
        gemiAdi: 'GOLDEN SHARK',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'Uluslararası / Palau',
        yukCinsi: 'Dökme Yük',
        islem: 'Tahliye',
        miktar: 28500,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Bulk / Product Carrier',
        bayrak: '🇵🇼 Palau',
        imoNo: 'IMO 9151383',
        iskeleNo: 'Güney Rıhtımı (Slab / Sac İskelesi)',
        progress: 0.50,
        lat: 36.7238,
        lng: 36.1968,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Tahliye Ediliyor (%50)',
      ),

      // 3. LİMAN İÇİ RÖMORKÖR VE KILAVUZ FİLOSU
      ShipData(
        id: '5',
        kategori: 'Rihtimdaki',
        gemiAdi: 'MED XXIV / MED U',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'İsdemir Römorkaj / Türkiye',
        yukCinsi: 'Liman Hizmetleri',
        islem: 'Yukleme',
        miktar: 0,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Harbour Tug (Römorkör)',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'MMSI 271001923',
        iskeleNo: 'İç Havuz İskelesi',
        progress: 1.0,
        lat: 36.7250,
        lng: 36.1910,
        heading: 90.0,
        speedKnots: 0.0,
        durum: 'Liman Nöbetinde / Aktif',
      ),
      ShipData(
        id: '6',
        kategori: 'Rihtimdaki',
        gemiAdi: 'KAPTAN BORA EKSI / AKKALE',
        tarihStr: '28.08 (Canlı)',
        firmaUlke: 'İsdemir Kılavuzluk / Türkiye',
        yukCinsi: 'Kılavuzluk & Palamar',
        islem: 'Yukleme',
        miktar: 0,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Pilot / Mooring Boat',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'MMSI 271004512',
        iskeleNo: 'Kılavuzluk İskelesi',
        progress: 1.0,
        lat: 36.7240,
        lng: 36.1980,
        heading: 0.0,
        speedKnots: 0.0,
        durum: 'Kılavuzluk Görevinde / Aktif',
      ),

      // 4. DEMİRDEKİ GEMİLER
      ShipData(
        id: '7',
        kategori: 'Demirdeki',
        gemiAdi: 'NEW HARVE',
        tarihStr: 'Demirde (Sırada)',
        firmaUlke: 'Lemiore / Rusya',
        yukCinsi: 'Pelet',
        islem: 'Tahliye',
        miktar: 75187,
        sortDate: DateTime(2026, 1, 1),
        gemiTipi: 'Panamax Bulk Carrier',
        bayrak: '🇵🇦 Panama',
        imoNo: 'IMO 9382109',
        iskeleNo: 'İsdemir Demir Sahası A-1',
        progress: 0.0,
        lat: 36.7380,
        lng: 36.1820,
        heading: 120.0,
        speedKnots: 0.1,
        durum: 'Demirde / Yanaşma Sırası Bekliyor',
      ),
      ShipData(
        id: '8',
        kategori: 'Demirdeki',
        gemiAdi: 'ANNA ROSE',
        tarihStr: 'Demirde (Hazır)',
        firmaUlke: 'AV Metal / Ukrayna',
        yukCinsi: 'Paket Sac',
        islem: 'Yukleme',
        miktar: 5000,
        sortDate: DateTime(2026, 8, 12),
        gemiTipi: 'General Cargo',
        bayrak: '🇧🇿 Belize',
        imoNo: 'IMO 8812039',
        iskeleNo: 'İsdemir Demir Sahası B-2',
        progress: 0.0,
        lat: 36.7450,
        lng: 36.1750,
        heading: 140.0,
        speedKnots: 0.1,
        durum: 'Demirde Bekliyor',
      ),

      // 5. BEKLENEN GEMİLER
      ShipData(
        id: '9',
        kategori: 'Beklenen',
        gemiAdi: 'MINERAL AJISAI',
        tarihStr: '29.08 (ETA 06:00)',
        firmaUlke: 'Vale / Brezilya',
        yukCinsi: 'Demir Cevheri',
        islem: 'Tahliye',
        miktar: 169884,
        sortDate: DateTime(2026, 8, 29),
        gemiTipi: 'Capesize Bulk Carrier',
        bayrak: '🇧🇸 Bahamalar',
        imoNo: 'IMO 9621004',
        iskeleNo: 'Planlanan: 1. Kömür İskelesi',
        progress: 0.0,
        lat: 36.7600,
        lng: 36.1400,
        heading: 135.0,
        speedKnots: 11.4,
        durum: 'İskenderun Körfezi Girişinde (11.4 kt)',
      ),
      ShipData(
        id: '10',
        kategori: 'Beklenen',
        gemiAdi: 'GENCO VIGILANT',
        tarihStr: '29.08 (ETA 14:30)',
        firmaUlke: 'Milpa / Kolombiya',
        yukCinsi: 'Met. Kok',
        islem: 'Tahliye',
        miktar: 36300,
        sortDate: DateTime(2026, 8, 29),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇲🇭 Marshall Adaları',
        imoNo: 'IMO 9712398',
        iskeleNo: 'Planlanan: 2. Rıhtım',
        progress: 0.0,
        lat: 36.7750,
        lng: 36.1200,
        heading: 142.0,
        speedKnots: 12.8,
        durum: 'Seyir Halinde (12.8 kt)',
      ),
    ];
  }
}
