class ShipData {
  final String id;
  final String kategori; // 'Rihtimdaki', 'Demirdeki', 'Beklenen'
  final String gemiAdi;
  final String tarihStr;
  final String firmaUlke;
  final String yukCinsi;
  final String islem; // 'Tahliye', 'Yukleme'
  final int miktar; // Ton
  final DateTime sortDate;
  
  // AIS & Canlı Radar Detayları
  final String gemiTipi; // 'Bulk Carrier', 'General Cargo', 'Tanker', 'Tug'
  final String bayrak; // Emoji ve Ülke
  final String imoNo;
  final String iskeleNo; // '1. İskele (Kömür)', '2. İskele (Slab)', 'Demir Sahası A'
  final double progress; // 0.0 - 1.0 (operasyon tamamlama)
  final double lat;
  final double lng;
  final double heading; // Rota açısı (derece)
  final double speedKnots;
  final String durum; // 'Tahliye Ediliyor', 'Yükleme Yapılıyor', 'Demirde Bekliyor', 'Yolda / Yaklaşıyor'

  const ShipData({
    required this.id,
    required this.kategori,
    required this.gemiAdi,
    required this.tarihStr,
    required this.firmaUlke,
    required this.yukCinsi,
    required this.islem,
    required this.miktar,
    required this.sortDate,
    required this.gemiTipi,
    required this.bayrak,
    required this.imoNo,
    required this.iskeleNo,
    required this.progress,
    required this.lat,
    required this.lng,
    required this.heading,
    required this.speedKnots,
    required this.durum,
  });

  static List<ShipData> getAllShips() {
    return [
      // RIHTIMDAKİ GEMİLER (Canlı İsdemir İskelelerinde Yanaşık)
      ShipData(
        id: '1',
        kategori: 'Rihtimdaki',
        gemiAdi: 'NAVIOS KOYO',
        tarihStr: '07.08 (17:42)',
        firmaUlke: 'BHP / Avustralya',
        yukCinsi: 'Kömür',
        islem: 'Tahliye',
        miktar: 169147,
        sortDate: DateTime(2026, 8, 7, 17, 42),
        gemiTipi: 'Bulk Carrier (Capesize)',
        bayrak: '🇵🇦 Panama',
        imoNo: 'IMO 9592484',
        iskeleNo: 'Ana Kömür İskelesi (1. Rıhtım)',
        progress: 0.85,
        lat: 36.7285,
        lng: 36.1915,
        heading: 42.0,
        speedKnots: 0.0,
        durum: 'Tahliye Ediliyor (%85)',
      ),
      ShipData(
        id: '2',
        kategori: 'Rihtimdaki',
        gemiAdi: 'NINA PETRAKIS',
        tarihStr: '09.08 (12:00)',
        firmaUlke: 'Peabody / Avustralya',
        yukCinsi: 'Kömür',
        islem: 'Tahliye',
        miktar: 80671,
        sortDate: DateTime(2026, 8, 9, 12, 0),
        gemiTipi: 'Bulk Carrier (Panamax)',
        bayrak: '🇲🇹 Malta',
        imoNo: 'IMO 9467811',
        iskeleNo: 'Cevher / Kömür İskelesi (2. Rıhtım)',
        progress: 0.62,
        lat: 36.7262,
        lng: 36.1932,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Tahliye Ediliyor (%62)',
      ),
      ShipData(
        id: '3',
        kategori: 'Rihtimdaki',
        gemiAdi: 'FWN ANTARCTIC',
        tarihStr: '08.08 (12:05)',
        firmaUlke: 'Laminoirs / Fransa',
        yukCinsi: 'Slab',
        islem: 'Yukleme',
        miktar: 9865,
        sortDate: DateTime(2026, 8, 8, 12, 5),
        gemiTipi: 'General Cargo',
        bayrak: '🇳🇱 Hollanda',
        imoNo: 'IMO 9324784',
        iskeleNo: 'Slab İskelesi (3. Rıhtım)',
        progress: 0.90,
        lat: 36.7248,
        lng: 36.1945,
        heading: 50.0,
        speedKnots: 0.0,
        durum: 'Yükleme Yapılıyor (%90)',
      ),
      ShipData(
        id: '4',
        kategori: 'Rihtimdaki',
        gemiAdi: 'MKK MADRID',
        tarihStr: '08.08 (09:45)',
        firmaUlke: 'Sideral BA / Birleşik Krallık',
        yukCinsi: 'Slab',
        islem: 'Yukleme',
        miktar: 20000,
        sortDate: DateTime(2026, 8, 8, 9, 45),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇱🇷 Liberya',
        imoNo: 'IMO 9654123',
        iskeleNo: 'Slab / Rulo İskelesi (4. Rıhtım)',
        progress: 0.45,
        lat: 36.7235,
        lng: 36.1960,
        heading: 48.0,
        speedKnots: 0.0,
        durum: 'Yükleme Yapılıyor (%45)',
      ),
      ShipData(
        id: '5',
        kategori: 'Rihtimdaki',
        gemiAdi: 'METIN IMAMOGLU',
        tarihStr: '14-15.08',
        firmaUlke: 'Erdemir / Türkiye',
        yukCinsi: 'Kok Tozu',
        islem: 'Tahliye',
        miktar: 4000,
        sortDate: DateTime(2026, 8, 14),
        gemiTipi: 'General Cargo',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 8912345',
        iskeleNo: 'İç İskele (5. Rıhtım)',
        progress: 0.70,
        lat: 36.7225,
        lng: 36.1970,
        heading: 52.0,
        speedKnots: 0.0,
        durum: 'Tahliye Ediliyor (%70)',
      ),
      ShipData(
        id: '6',
        kategori: 'Rihtimdaki',
        gemiAdi: 'HACI MEHMET KAPTAN',
        tarihStr: '09.08 (01:40)',
        firmaUlke: 'Erdemir / Türkiye',
        yukCinsi: 'Rulo Sac',
        islem: 'Yukleme',
        miktar: 3170,
        sortDate: DateTime(2026, 8, 9, 1, 40),
        gemiTipi: 'General Cargo',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 9123847',
        iskeleNo: 'Mamul İskelesi (6. Rıhtım)',
        progress: 0.35,
        lat: 36.7218,
        lng: 36.1985,
        heading: 55.0,
        speedKnots: 0.0,
        durum: 'Yükleme Yapılıyor (%35)',
      ),
      ShipData(
        id: '7',
        kategori: 'Rihtimdaki',
        gemiAdi: 'TAMREY S',
        tarihStr: '08.08 / laycan 13-14.08',
        firmaUlke: 'Erdemir / Türkiye',
        yukCinsi: 'Slab / R.Sac / Kuvarsit',
        islem: 'Yukleme',
        miktar: 29800,
        sortDate: DateTime(2026, 8, 8),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 9481920',
        iskeleNo: 'Çok Amaçlı İskele (7. Rıhtım)',
        progress: 0.50,
        lat: 36.7210,
        lng: 36.1995,
        heading: 60.0,
        speedKnots: 0.0,
        durum: 'Yükleme Yapılıyor (%50)',
      ),

      // DEMİRDEKİ GEMİLER (İsdemir Demirleme Sahasında Bekleyenler)
      ShipData(
        id: '8',
        kategori: 'Demirdeki',
        gemiAdi: 'NEW HARVE',
        tarihStr: 'Demirde (Hazır)',
        firmaUlke: 'Lemiore / Rusya',
        yukCinsi: 'Pelet',
        islem: 'Tahliye',
        miktar: 75187,
        sortDate: DateTime(2026, 1, 1),
        gemiTipi: 'Bulk Carrier (Panamax)',
        bayrak: '🇵🇦 Panama',
        imoNo: 'IMO 9382109',
        iskeleNo: 'İsdemir Demir Sahası A-2',
        progress: 0.0,
        lat: 36.7380,
        lng: 36.1820,
        heading: 120.0,
        speedKnots: 0.2,
        durum: 'Rıhtım Sırası Bekliyor',
      ),
      ShipData(
        id: '9',
        kategori: 'Demirdeki',
        gemiAdi: 'ANNA ROSE',
        tarihStr: 'laycan 12-13.08',
        firmaUlke: 'AV Metal / Ukrayna',
        yukCinsi: 'Paket Sac',
        islem: 'Yukleme',
        miktar: 5000,
        sortDate: DateTime(2026, 8, 12),
        gemiTipi: 'General Cargo',
        bayrak: '🇧🇿 Belize',
        imoNo: 'IMO 8812039',
        iskeleNo: 'İsdemir Demir Sahası B-1',
        progress: 0.0,
        lat: 36.7450,
        lng: 36.1750,
        heading: 140.0,
        speedKnots: 0.1,
        durum: 'Demirde Bekliyor',
      ),

      // BEKLENEN GEMİLER (Seyir Halindeki / Limana Yaklaşan Gemiler)
      ShipData(
        id: '10',
        kategori: 'Beklenen',
        gemiAdi: 'MINERAL AJISAI',
        tarihStr: '18.08 (ETA 06:00)',
        firmaUlke: 'Vale / Brezilya',
        yukCinsi: 'Cevher',
        islem: 'Tahliye',
        miktar: 169884,
        sortDate: DateTime(2026, 8, 18),
        gemiTipi: 'Bulk Carrier (Capesize)',
        bayrak: '🇧🇸 Bahamalar',
        imoNo: 'IMO 9621004',
        iskeleNo: 'Planlanan: 1. Rıhtım',
        progress: 0.0,
        lat: 36.7600,
        lng: 36.1400,
        heading: 135.0,
        speedKnots: 11.4,
        durum: 'İskenderun Körfezi Girişinde (11.4 kt)',
      ),
      ShipData(
        id: '11',
        kategori: 'Beklenen',
        gemiAdi: 'GENCO VIGILANT',
        tarihStr: '18.08 (ETA 14:30)',
        firmaUlke: 'Milpa / Kolombiya',
        yukCinsi: 'Met. Kok',
        islem: 'Tahliye',
        miktar: 36300,
        sortDate: DateTime(2026, 8, 18),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇲🇭 Marshall Adaları',
        imoNo: 'IMO 9712398',
        iskeleNo: 'Planlanan: 2. Rıhtım',
        progress: 0.0,
        lat: 36.7750,
        lng: 36.1200,
        heading: 142.0,
        speedKnots: 12.8,
        durum: 'Seyir Halinde (12.8 kt)',
      ),
      ShipData(
        id: '12',
        kategori: 'Beklenen',
        gemiAdi: 'CHEMICAL EXPLORER',
        tarihStr: '17.08 (laycan)',
        firmaUlke: 'Koppers International',
        yukCinsi: 'Katran',
        islem: 'Yukleme',
        miktar: 11000,
        sortDate: DateTime(2026, 8, 17),
        gemiTipi: 'Chemical Tanker',
        bayrak: '🇸🇬 Singapur',
        imoNo: 'IMO 9518290',
        iskeleNo: 'Planlanan: Sıvı Yük İskelesi',
        progress: 0.0,
        lat: 36.7900,
        lng: 36.0900,
        heading: 130.0,
        speedKnots: 9.6,
        durum: 'Seyir Halinde (9.6 kt)',
      ),
      ShipData(
        id: '13',
        kategori: 'Beklenen',
        gemiAdi: 'S SAMBA',
        tarihStr: '19.08',
        firmaUlke: 'Taqa / Rusya',
        yukCinsi: 'PCI Kömür',
        islem: 'Tahliye',
        miktar: 80000,
        sortDate: DateTime(2026, 8, 19),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇱🇷 Liberya',
        imoNo: 'IMO 9329012',
        iskeleNo: 'Planlanan: 1. Rıhtım',
        progress: 0.0,
        lat: 36.8100,
        lng: 36.0500,
        heading: 125.0,
        speedKnots: 13.2,
        durum: 'Akdeniz Seyrinde (13.2 kt)',
      ),
      ShipData(
        id: '14',
        kategori: 'Beklenen',
        gemiAdi: 'SARE IMAMOGLU',
        tarihStr: 'laycan 12-13.08',
        firmaUlke: 'İsdemir / Türkiye',
        yukCinsi: 'Rulo Sac',
        islem: 'Yukleme',
        miktar: 4350,
        sortDate: DateTime(2026, 8, 12),
        gemiTipi: 'General Cargo',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 9043219',
        iskeleNo: 'Planlanan: 4. Rıhtım',
        progress: 0.0,
        lat: 36.7550,
        lng: 36.1600,
        heading: 110.0,
        speedKnots: 8.5,
        durum: 'Yanaşma Manevrasında',
      ),
      ShipData(
        id: '15',
        kategori: 'Beklenen',
        gemiAdi: 'LUCY OLDENDORFF',
        tarihStr: '12.09',
        firmaUlke: 'Anglo / Avustralya',
        yukCinsi: 'Kömür',
        islem: 'Tahliye',
        miktar: 170667,
        sortDate: DateTime(2026, 9, 12),
        gemiTipi: 'Capesize Bulk Carrier',
        bayrak: '🇵🇹 Portekiz',
        imoNo: 'IMO 9821034',
        iskeleNo: 'Planlanan: 1. Rıhtım',
        progress: 0.0,
        lat: 36.8500,
        lng: 35.9500,
        heading: 120.0,
        speedKnots: 14.0,
        durum: 'Seyir Halinde',
      ),
    ];
  }
}
