class ShipData {
  final String id;
  final String kategori; // 'Rihtimdaki', 'Demirdeki', 'Beklenen', 'Ayrilan'
  final String gemiAdi;
  final String tarihStr;
  final String firmaUlke;
  final String yukCinsi;
  final String islem; // 'Tahliye', 'Yukleme'
  final int miktar; // Ton
  final DateTime sortDate;
  
  // AIS & Canlı Radar Detayları
  final String gemiTipi;
  final String bayrak;
  final String imoNo;
  final String iskeleNo;
  final double progress; // 0.0 - 1.0
  final double lat;
  final double lng;
  final double heading;
  final double speedKnots;
  final String durum;

  const ShipData({
    required this.id,
    required this.kategori,
    required this.gemiAdi,
    required this.tarihStr,
    required this.firmaUlke,
    required this.yukCinsi,
    required this.islem,
    required this.miktar,
    required this.sortDate,
    required this.gemiTipi,
    required this.bayrak,
    required this.imoNo,
    required this.iskeleNo,
    required this.progress,
    required this.lat,
    required this.lng,
    required this.heading,
    required this.speedKnots,
    required this.durum,
  });

  factory ShipData.fromJson(Map<String, dynamic> item) {
    return ShipData(
      id: item['id']?.toString() ?? '',
      kategori: item['kategori'] ?? 'Rihtimdaki',
      gemiAdi: item['gemiAdi'] ?? '',
      tarihStr: item['tarihStr'] ?? '',
      firmaUlke: item['firmaUlke'] ?? '',
      yukCinsi: item['yukCinsi'] ?? '',
      islem: item['islem'] ?? 'Tahliye',
      miktar: item['miktar'] is int ? item['miktar'] : (int.tryParse(item['miktar'].toString()) ?? 0),
      sortDate: DateTime.now(),
      gemiTipi: item['gemiTipi'] ?? 'Bulk Carrier',
      bayrak: item['bayrak'] ?? '🇹🇷 Türkiye',
      imoNo: item['imoNo'] ?? '',
      iskeleNo: item['iskeleNo'] ?? '',
      progress: (item['progress'] is num) ? (item['progress'] as num).toDouble() : 0.0,
      lat: (item['lat'] is num) ? (item['lat'] as num).toDouble() : 36.7264,
      lng: (item['lng'] is num) ? (item['lng'] as num).toDouble() : 36.1863,
      heading: (item['heading'] is num) ? (item['heading'] as num).toDouble() : 45.0,
      speedKnots: (item['speedKnots'] is num) ? (item['speedKnots'] as num).toDouble() : 0.0,
      durum: item['durum'] ?? 'Aktif',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'kategori': kategori,
      'gemiAdi': gemiAdi,
      'tarihStr': tarihStr,
      'firmaUlke': firmaUlke,
      'yukCinsi': yukCinsi,
      'islem': islem,
      'miktar': miktar,
      'gemiTipi': gemiTipi,
      'bayrak': bayrak,
      'imoNo': imoNo,
      'iskeleNo': iskeleNo,
      'progress': progress,
      'lat': lat,
      'lng': lng,
      'heading': heading,
      'speedKnots': speedKnots,
      'durum': durum,
    };
  }

  static List<ShipData> getAllShips() {
    return [
      // 1. DIŞ UZUN İSKELEDEKİ GEMİ (Kimyasal Tanker)
      ShipData(
        id: '1',
        kategori: 'Rihtimdaki',
        gemiAdi: 'CHEMICAL EXPLORER',
        tarihStr: 'Yanaşık (Canlı)',
        firmaUlke: 'Koppers / Singapur',
        yukCinsi: 'Katran / Kimyasal Sıvı',
        islem: 'Yukleme',
        miktar: 11000,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Chemical Tanker',
        bayrak: '🇸🇬 Singapur',
        imoNo: 'IMO 9518290',
        iskeleNo: 'Dış Uzun İskele (Tanker Başı)',
        progress: 0.85,
        lat: 36.7264,
        lng: 36.1863,
        heading: 245.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Yükleme Yapılıyor (%85)',
      ),

      // 2. İÇ RIHTIMLARDAKİ ANA GEMİLER
      ShipData(
        id: '2',
        kategori: 'Rihtimdaki',
        gemiAdi: 'MV IONIC SPIRIT',
        tarihStr: 'Yanaşık (Canlı)',
        firmaUlke: 'Milpa / Kolombiya',
        yukCinsi: 'Met. Kok Kömürü',
        islem: 'Tahliye',
        miktar: 33000,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Supramax Bulk Carrier',
        bayrak: '🇲🇭 Marshall Adaları',
        imoNo: 'IMO 9514200',
        iskeleNo: '1. Rıhtım (Kuzey İskelesi)',
        progress: 0.70,
        lat: 36.7255,
        lng: 36.1952,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Tahliye Ediliyor (%70)',
      ),
      ShipData(
        id: '3',
        kategori: 'Rihtimdaki',
        gemiAdi: 'GALA A',
        tarihStr: 'Yanaşık (Canlı)',
        firmaUlke: 'Arel Shipping / Türkiye',
        yukCinsi: 'Genel Kargo / Sac',
        islem: 'Yukleme',
        miktar: 5500,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'General Cargo Ship',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'IMO 8822040',
        iskeleNo: 'İç Parmak İskele (Finger Quay)',
        progress: 0.95,
        lat: 36.7248,
        lng: 36.1960,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Yükleme Tamamlanmak Üzere (%95)',
      ),
      ShipData(
        id: '4',
        kategori: 'Rihtimdaki',
        gemiAdi: 'GOLDEN SHARK',
        tarihStr: 'Yanaşık (Canlı)',
        firmaUlke: 'Uluslararası / Palau',
        yukCinsi: 'Dökme Yük',
        islem: 'Tahliye',
        miktar: 28500,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Bulk / Product Carrier',
        bayrak: '🇵🇼 Palau',
        imoNo: 'IMO 9151383',
        iskeleNo: 'Güney Rıhtımı (Slab / Sac İskelesi)',
        progress: 0.55,
        lat: 36.7238,
        lng: 36.1968,
        heading: 45.0,
        speedKnots: 0.0,
        durum: 'Yanaşık / Tahliye Ediliyor (%55)',
      ),

      // 3. LİMAN İÇİ RÖMORKÖR VE KILAVUZ FİLOSU
      ShipData(
        id: '5',
        kategori: 'Rihtimdaki',
        gemiAdi: 'MED XXIV / MED U',
        tarihStr: 'Liman İçi Nöbette',
        firmaUlke: 'İsdemir Römorkaj / Türkiye',
        yukCinsi: 'Liman Hizmetleri',
        islem: 'Yukleme',
        miktar: 0,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Harbour Tug (Römorkör)',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'MMSI 271001923',
        iskeleNo: 'İç Havuz İskelesi',
        progress: 1.0,
        lat: 36.7250,
        lng: 36.1910,
        heading: 90.0,
        speedKnots: 0.0,
        durum: 'Liman Nöbetinde / Aktif',
      ),
      ShipData(
        id: '6',
        kategori: 'Rihtimdaki',
        gemiAdi: 'KAPTAN BORA EKSI / AKKALE',
        tarihStr: 'Liman İçi Nöbette',
        firmaUlke: 'İsdemir Kılavuzluk / Türkiye',
        yukCinsi: 'Kılavuzluk & Palamar',
        islem: 'Yukleme',
        miktar: 0,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'Pilot / Mooring Boat',
        bayrak: '🇹🇷 Türkiye',
        imoNo: 'MMSI 271004512',
        iskeleNo: 'Kılavuzluk İskelesi',
        progress: 1.0,
        lat: 36.7240,
        lng: 36.1980,
        heading: 0.0,
        speedKnots: 0.0,
        durum: 'Kılavuzluk Görevinde / Aktif',
      ),

      // 4. DEMİRDEKİ GEMİLER
      ShipData(
        id: '7',
        kategori: 'Demirdeki',
        gemiAdi: 'NEW HARVE',
        tarihStr: 'Demirde (Sırada)',
        firmaUlke: 'Lemiore / Rusya',
        yukCinsi: 'Pelet',
        islem: 'Tahliye',
        miktar: 75187,
        sortDate: DateTime(2026, 1, 1),
        gemiTipi: 'Panamax Bulk Carrier',
        bayrak: '🇵🇦 Panama',
        imoNo: 'IMO 9382109',
        iskeleNo: 'İsdemir Demir Sahası A-1',
        progress: 0.0,
        lat: 36.7380,
        lng: 36.1820,
        heading: 120.0,
        speedKnots: 0.1,
        durum: 'Demirde / Yanaşma Sırası Bekliyor',
      ),
      ShipData(
        id: '8',
        kategori: 'Demirdeki',
        gemiAdi: 'ANNA ROSE',
        tarihStr: 'Demirde (Hazır)',
        firmaUlke: 'AV Metal / Ukrayna',
        yukCinsi: 'Paket Sac',
        islem: 'Yukleme',
        miktar: 5000,
        sortDate: DateTime(2026, 8, 12),
        gemiTipi: 'General Cargo',
        bayrak: '🇧🇿 Belize',
        imoNo: 'IMO 8812039',
        iskeleNo: 'İsdemir Demir Sahası B-2',
        progress: 0.0,
        lat: 36.7450,
        lng: 36.1750,
        heading: 140.0,
        speedKnots: 0.1,
        durum: 'Demirde Bekliyor',
      ),

      // 5. YAKLAŞAN / BEKLENEN GEMİLER
      ShipData(
        id: '9',
        kategori: 'Beklenen',
        gemiAdi: 'MINERAL AJISAI',
        tarihStr: 'Yaklaşıyor (ETA 45 dk)',
        firmaUlke: 'Vale / Brezilya',
        yukCinsi: 'Demir Cevheri',
        islem: 'Tahliye',
        miktar: 169884,
        sortDate: DateTime(2026, 8, 29),
        gemiTipi: 'Capesize Bulk Carrier',
        bayrak: '🇧🇸 Bahamalar',
        imoNo: 'IMO 9621004',
        iskeleNo: 'Planlanan: 1. Kömür İskelesi',
        progress: 0.0,
        lat: 36.7520,
        lng: 36.1550,
        heading: 135.0,
        speedKnots: 8.5,
        durum: 'Körfezde / İsdemir Limanına Yaklaşıyor (8.5 kt)',
      ),
      ShipData(
        id: '10',
        kategori: 'Beklenen',
        gemiAdi: 'GENCO VIGILANT',
        tarihStr: 'Yolda (ETA ~3 Saat)',
        firmaUlke: 'Milpa / Kolombiya',
        yukCinsi: 'Met. Kok',
        islem: 'Tahliye',
        miktar: 36300,
        sortDate: DateTime(2026, 8, 29),
        gemiTipi: 'Bulk Carrier',
        bayrak: '🇲🇭 Marshall Adaları',
        imoNo: 'IMO 9712398',
        iskeleNo: 'Planlanan: 2. Rıhtım',
        progress: 0.0,
        lat: 36.7850,
        lng: 36.1100,
        heading: 142.0,
        speedKnots: 12.8,
        durum: 'İskenderun Körfezi Girişinde Seyirde (12.8 kt)',
      ),

      // 6. SON AYRILAN GEMİLER
      ShipData(
        id: '11',
        kategori: 'Ayrilan',
        gemiAdi: 'LADY MARIA',
        tarihStr: 'Ayrıldı (Bugün 16:30)',
        firmaUlke: 'Mediterranean / İtalya',
        yukCinsi: 'Rulo Sac',
        islem: 'Yukleme',
        miktar: 14200,
        sortDate: DateTime(2026, 8, 28),
        gemiTipi: 'General Cargo',
        bayrak: '🇵🇦 Panama',
        imoNo: 'IMO 9481231',
        iskeleNo: '3. Rıhtımından Ayrıldı',
        progress: 1.0,
        lat: 36.7100,
        lng: 36.1200,
        heading: 260.0,
        speedKnots: 13.5,
        durum: 'Limandan Ayrıldı / Akdeniz Açıklarında Seyirde (13.5 kt)',
      ),
    ];
  }
}
