// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvf6cKildF6QwHduR9aDREoTtay609MEA',
    appId: '1:273895046417:web:5bc6a207c3fbc8d55760b0',
    messagingSenderId: '273895046417',
    projectId: 'isdemirops',
    authDomain: 'isdemirops.firebaseapp.com',
    storageBucket: 'isdemirops.firebasestorage.app',
    measurementId: 'G-XSQ4MM9K89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBeZ2jcAztqF2ILqTwVsgks4LlUXRc2Y8',
    appId: '1:273895046417:android:9ea802e2628061225760b0',
    messagingSenderId: '273895046417',
    projectId: 'isdemirops',
    storageBucket: 'isdemirops.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fSNK6lTvJMHPJkv3sOYlAeZLotdAcNQ',
    appId: '1:273895046417:ios:4ccba7d0be0ae5ac5760b0',
    messagingSenderId: '273895046417',
    projectId: 'isdemirops',
    storageBucket: 'isdemirops.firebasestorage.app',
    iosBundleId: 'com.example.myStarterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_fSNK6lTvJMHPJkv3sOYlAeZLotdAcNQ',
    appId: '1:273895046417:ios:4ccba7d0be0ae5ac5760b0',
    messagingSenderId: '273895046417',
    projectId: 'isdemirops',
    storageBucket: 'isdemirops.firebasestorage.app',
    iosBundleId: 'com.example.myStarterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvf6cKildF6QwHduR9aDREoTtay609MEA',
    appId: '1:273895046417:web:308070e7513cf4305760b0',
    messagingSenderId: '273895046417',
    projectId: 'isdemirops',
    authDomain: 'isdemirops.firebaseapp.com',
    storageBucket: 'isdemirops.firebasestorage.app',
    measurementId: 'G-22TN1RKVNE',
  );
}
